import yuanChingLogo from '../yuanchinglogo.png';
import yijcLogo from '../yijclogo.png';
export const testimonials = [
  {
    title: 'Yuan Ching Secondary School',
    level: 'Secondary School',
    years: '2021 – 2024',
    logo: yuanChingLogo,
    src: yuanChingLogo,
    aspect: 1,
    paragraphs: [
      'Min Htut Khaing was a student of Yuan Ching Secondary School from January 2021 to December 2024. He sat for the Singapore-Cambridge GCE O-Level Examination in 2024.',
      'Min is a friendly and quiet student who enjoys interacting with his close friends. He is helpful as he will do his best to help those in need. He works well with his friends in groups assigned to him. Min is a well-behaved student who does what he is tasked to do. He is attentive in lessons and has a positive attitude towards learning. With an earnest attitude to learn, Min has continued to work hard to improve his grades with a clear goal in mind and a will to succeed.',
      'Min is very passionate about his Co-Curriculum Activities (CCA) which is Basketball. In the four years of his basketball journey, he represented his school regionally in the West-Zone region in 2022 as a junior and in 2024 as a senior in the National School Games in both C and B divisions respectively, while also participating in friendly games against other schools. He has strong belief in his CCA motto “Scholar Sportsman” as he does his best to balance between basketball training and studies. He has shown that he can balance his grades while also improving his skills in basketball. As a senior in the upper secondary CCA executive committee, he helped his juniors by guiding them in training and taking responsibility to educate and teach them about the morality that they are a student before they are an athlete. By building a good relationship with his juniors and his peers, he is liked by them.',
      'Min has shown genuine interest in helping the community and the environment. He has partnered up with his two friends and started a routine of going to the park every once a week and collecting trash for their Values-In-Action project. Min’s dedication as a reading ambassador in his class has truly made a positive impact on his class. His collaborative efforts with classmates in donating books to his reading corner have not only enriched his literary resources but also fostered a love for reading among students. Min’s commitment to promoting reading reflects his outstanding leadership and generosity, creating a vibrant learning environment for everyone. Min has also participated in the Queens Commonwealth Essay competition in 2023 and 2024 due to his liking for writing and has achieved both bronze and silver awards respectively during his participation in the competition. Additionally, he participated in the Ngee Ann Polytechnic Math Challenge in 2024 with his peers, earning the school a silver trophy in his team challenge. Min continued to challenge himself and attained Silver in the National Youth Achievement Award (NYAA) 2024.',
      'Min is a hardworking student who tries his best in everything he does. His friendliness and kindness make him personable to his classmates. His character and experiences has helped him in becoming a well-motivated and resilient student in both his studies and character.'
    ],
  },
  {
    title: 'Yishun Innova Junior College',
    level: 'Junior College',
    years: '2025 – 2026',
    logo: yijcLogo,
    src: yijcLogo,
    aspect: 1,
    paragraphs: [
      "Min Htut Khaing was a student of Yishun Innova Junior College from 2025 to 2026, where he studied in the Science Faculty.",
      "Min was a proactive and self-motivated learner who displayed a strong aptitude for technology and analytical thinking.",
      "His intellectual curiosity was evident in his selection as a Centre for Strategic Infocomm Technologies (CSIT) scholarship nominee, which recognised his potential in computing and cybersecurity. He actively sought opportunities to apply concepts he had learnt in class to real-world challenges, participating in prestigious events such as the National University of Singapore's Humanities Challenge 2025, the Intel Global AI Impact Festival 2026, and the Defence Science and Technology Agency (DSTA) BrainHack 2026. He also clinched first place in the Nee Soon AI and Innovation Challenge 2026 (Category A – Schools), a testament to his ability to apply artificial intelligence concepts competitively. His commitment to developing his technical abilities was further reflected in his consistent performance in the Bebras Challenge Singapore, an international informatics and computational thinking challenge organised by NIE (NTU), NUS Computing, and SIMCC, where he achieved Bronze Awards in both 2025 and 2026. He also completed the ICDL National Digital Explorer Programme 2025–2026, earning internationally recognised certifications in Spreadsheets, Presentation, and Big Data after completing all three eLearning modules and certification tests. Additionally, he attended the BuildingBloCS March Conference, where he deepened his skills in computational thinking and programming. In class, Min consistently demonstrated the ability to synthesise diverse perspectives and offer creative solutions during group discussions.",
      "As a dedicated member of Makers' Academy, Min exhibited a strong passion for innovation and digital making. He actively participated in major college showcases, including the YI Makers' Faire and YI Festival, presenting projects that combined technical expertise with creative problem-solving. His commitment extended beyond the college, as he represented it in external events such as the Defence Science and Technology Agency CODE_EXP Mobile App Development Hackathon, where he showcased his technical proficiency and innovative thinking. Through his sustained involvement in Makers' Academy, Min developed substantial knowledge of computational thinking and emerging technologies, applying these skills meaningfully across various contexts.",
      "Min demonstrated commendable leadership skills through his contributions to college events. As a facilitator at the Digital Literacy Games Station for the College Race during the Yishun Innova Junior College Orientation Programme, he guided incoming JC1 students through digital literacy challenges with clarity and enthusiasm. His ability to communicate effectively and maintain a positive atmosphere ensured the smooth execution of activities and motivated participants.",
      "Beyond formal leadership roles, Min often displayed initiative and a collaborative spirit in group settings, steering discussions toward productive outcomes and helping peers navigate complex problems. Min's reliability and genuine concern for those around him earned him the trust of his peers, and these qualities laid a meaningful foundation for his continued growth as a leader.",
      "Min contributed significantly to the college and the wider community through his involvement in community service initiatives. During the Yishun Innova Junior College Orientation Programme, his role at the Digital Literacy Games Station for the College Race centred on creating a welcoming and supportive experience for incoming JC1 students. He was attentive to students who struggled, offering patient guidance and encouragement to help them feel at ease in their new environment. Through Makers' Academy's Values in Action initiatives, he also introduced primary school students to simple coding concepts, demonstrating an ability to adapt his communication style to suit a younger audience. These experiences revealed a side of Min that went beyond his technical strengths — genuine care for others and a willingness to invest time in supporting those around him, reflecting a quiet but sincere commitment to service.",
      "Min maintained a positive outlook even when faced with academic or technical challenges. He was reliable and conscientious, often taking the initiative to support his peers in both academic and co-curricular settings. His humility and growth mindset allowed him to seek feedback actively and constantly look for ways to improve his own performance.",
      "Min related well to his tutors and peers. His affable and helpful nature made him a positive influence within the college.",
      "Overall, Min brings sincerity and quiet determination to everything he undertakes, embodying the kind of character that inspires confidence in those around him. Min is poised to embrace new challenges and make meaningful contributions in his future endeavours."
    ],
  },
];
